import { Lock, Database, EyeOff, ShieldCheck } from 'lucide-react'

export default function Privacy() {
  const policies = [
    {
      icon: Database,
      title: 'Data Collected',
      description: 'When you perform a scan, we temporarily collect the target domain names and IP addresses required to execute the OSINT queries and vulnerability analysis.',
      color: 'matrix'
    },
    {
      icon: EyeOff,
      title: 'Data Usage',
      description: 'The collected data is used exclusively for the purpose of generating the security analysis report requested by the user. We do not track targets for our own purposes.',
      color: 'cyber'
    },
    {
      icon: Lock,
      title: 'No Data Selling',
      description: 'We absolutely do not sell user data or scan results to third parties, data brokers, or marketing agencies. Your reconnaissance data belongs to you.',
      color: 'neon'
    },
    {
      icon: ShieldCheck,
      title: 'Data Security',
      description: 'All intelligence data is handled securely in transit and at rest. Reports generated by the platform are kept confidential and are securely processed.',
      color: 'matrix'
    }
  ]

  return (
    <div className="animate-fade-in max-w-4xl mx-auto">
      <div className="flex items-center gap-3 mb-10">
        <div className="w-12 h-12 rounded-xl bg-cyber-400/10 border border-cyber-400/20 flex items-center justify-center">
          <Lock className="w-6 h-6 text-cyber-400" />
        </div>
        <div>
          <h1 className="text-3xl font-display font-bold text-white tracking-wider uppercase">Privacy Policy</h1>
          <p className="text-sm font-mono text-gray-500 mt-1">How we protect your data and scan intelligence</p>
        </div>
      </div>

      <div className="glass-card overflow-hidden">
        <div className="p-6 border-b border-white/5 bg-surface-900/50">
          <p className="text-sm font-mono text-gray-400 leading-relaxed">
            At ReconShield, we take data privacy as seriously as we take cybersecurity. We operate strictly on a need-to-know basis. This policy outlines our commitment to protecting the information you provide while using our domain analysis tool.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-white/5">
          {policies.map((p, i) => {
            const Icon = p.icon
            const colors = {
              matrix: 'text-matrix-400 bg-matrix-400/10',
              cyber: 'text-cyber-400 bg-cyber-400/10',
              neon: 'text-neon-400 bg-neon-400/10',
            }
            return (
              <div key={i} className="p-8 group hover:bg-white/[0.02] transition-colors">
                <div className={`w-10 h-10 rounded-lg flex items-center justify-center mb-4 ${colors[p.color]}`}>
                  <Icon className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-heading font-semibold text-white uppercase tracking-wide mb-2">{p.title}</h3>
                <p className="text-sm font-mono text-gray-500 leading-relaxed">{p.description}</p>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
