export const dmarc = {
  "term": "DMARC",
  "title": "DMARC Explained: Enforcing Domain Reputation",
  "description": "Discover how DMARC ties SPF and DKIM together, provides reporting, and allows organizations to definitively block phishing attacks.",
  "keyTakeaways": [
    "DMARC requires alignment of From headers with SPF and/or DKIM domains.",
    "DMARC policies (none, quarantine, reject) tell receiving servers how to handle failures.",
    "DMARC provides XML feedback reports (RUA/RUF) detailing all sending sources."
  ],
  "history": {
    "origin": "DMARC was drafted in 2012 by an industry consortium (including PayPal, Google, and Microsoft) to solve the limits of SPF and DKIM in blocking domain spoofing.",
    "evolution": "In 2015, the IETF published DMARC as RFC 7489, establishing it as the standard mechanism for domain-level email policy enforcement.",
    "adoption": "DMARC enforcement is now the gold standard for brand protection, required by security compliance standards globally."
  },
  "deepDive": {
    "protocol": "DMARC operates at the DNS layer using a TXT record at '_dmarc.domain.com'. It evaluates the alignment of the visible From header.",
    "architecture": "When an email is received, DMARC checks: 1. Did SPF pass and align? 2. Did DKIM pass and align? If either condition is true, DMARC passes.",
    "standards": "Standardized under RFC 7489, featuring a syntax structure using key-value tags (e.g., p, rua, pct, adim)."
  },
  "security": {
    "attacks": "Prevents direct domain spoofing attacks where threat actors forge the visible From header to pretend to be an organization.",
    "threatModel": "Addresses phishing, brand abuse, and executive impersonation (BEC).",
    "detection": "Monitoring XML reports generated by receiving servers, highlighting unauthorized senders."
  },
  "realWorld": {
    "enterprise": "Enterprises transition from 'p=none' to 'p=reject' over several months to safely secure their outbound mail streams.",
    "incidents": "Organizations lacking DMARC policies are frequently spoofed in massive consumer phishing campaigns.",
    "misconfigurations": "Deploying 'p=reject' too quickly before aligning legitimate marketing servers, resulting in corporate email outages."
  },
  "usage": {
    "steps": "Publish a DMARC TXT record at '_dmarc.domain.com' with 'p=none', monitor reports, align sources, and advance to 'p=reject'.",
    "bestPractices": "Always parse DMARC XML reports using a reporting tool and enforce strict alignment for DKIM."
  },
  "mistakes": {
    "errors": "Using incorrect syntax in the DMARC record, which invalidates the policy.",
    "weaknesses": "Failing to configure a valid email in the RUA tag, leaving the domain owner blind to sending volumes.",
    "troubleshooting": "Check DMARC records via our Email Analyzer and ensure DNS propagation is complete."
  },
  "comparisonTable": {
    "title": "DMARC Policies",
    "headers": [
      "Policy",
      "Enforcement Level",
      "Action on Failure",
      "Use Case"
    ],
    "rows": [
      [
        "p=none",
        "None (Monitoring)",
        "Delivered to inbox (log only)",
        "Initial setup and data gathering"
      ],
      [
        "p=quarantine",
        "Moderate",
        "Sent to spam/junk folder",
        "Testing alignment and staging blocks"
      ],
      [
        "p=reject",
        "Maximum",
        "Blocked at SMTP gateway",
        "Complete protection against domain spoofing"
      ]
    ]
  },
  "references": [
    {
      "title": "RFC 7489 - Domain-based Message Authentication, Reporting, and Conformance",
      "url": "https://datatracker.ietf.org/doc/html/rfc7489"
    }
  ],
  "faqs": [
    {
      "q": "What is DMARC?",
      "url": "",
      "a": "Domain-based Message Authentication, Reporting, and Conformance, an email security protocol."
    },
    {
      "q": "What is DMARC alignment?",
      "url": "",
      "a": "The requirement that the domain in the From header matches the domain authenticated by SPF and/or DKIM."
    },
    {
      "q": "What is the p= tag?",
      "url": "",
      "a": "The policy tag specifying how receivers should handle emails that fail DMARC checks."
    },
    {
      "q": "What is the difference between RUA and RUF?",
      "url": "",
      "a": "RUA collects aggregate daily XML reports; RUF collects real-time forensic failure samples (often disabled due to privacy)."
    },
    {
      "q": "Does DMARC stop all spam?",
      "url": "",
      "a": "No, it only stops people from spoofing YOUR domain name. It does not stop spam sent from other domains."
    },
    {
      "q": "What is BIMI?",
      "url": "",
      "a": "Brand Indicators for Message Identification, showing your logo in verified inboxes if you have a p=reject/quarantine DMARC policy."
    },
    {
      "q": "How do I check my DMARC record?",
      "url": "",
      "a": "Use our online Email Security Analyzer to verify your DMARC DNS settings."
    },
    {
      "q": "What is the pct tag?",
      "url": "",
      "a": "Percentage tag, allowing you to apply DMARC policy to a fraction of failing messages (e.g., pct=50)."
    },
    {
      "q": "Why did my DMARC fail?",
      "url": "",
      "a": "Typically because the sending system failed SPF/DKIM or did not have domain alignment with the From header."
    },
    {
      "q": "Can I use DMARC for subdomains?",
      "url": "",
      "a": "Yes, using the sp= tag to define policies for subdomains separate from the root domain."
    },
    {
      "q": "What is strict vs relaxed alignment?",
      "url": "",
      "a": "Relaxed allows subdomains to align with root domains; strict requires an exact domain match."
    },
    {
      "q": "Who sends DMARC reports?",
      "url": "",
      "a": "Receiving email providers (Google, Microsoft, Yahoo) send aggregate XML reports to your designated RUA address."
    },
    {
      "q": "Is DMARC difficult to implement?",
      "url": "",
      "a": "Publishing the record is easy, but reaching p=reject without blocking legitimate emails requires careful report analysis."
    },
    {
      "q": "Does DMARC check inbound or outbound mail?",
      "url": "",
      "a": "You publish DMARC to protect your outbound mail reputation. Receiving servers check it to inspect inbound mail."
    },
    {
      "q": "What is the adim tag?",
      "url": "",
      "a": "This is a typo; the alignment tags are aspf and adkim, setting strict or relaxed alignment."
    }
  ],
  "relatedTerms": [
    "spf",
    "dkim"
  ],
  "cta": {
    "title": "Check DMARC Enforcement",
    "desc": "Verify if your domain is protected against executive impersonation.",
    "tool": "Email Security Analyzer",
    "url": "/tools/email-security"
  }
};
