import { ToolMetadata } from '@/types/tool';

export interface FlagshipTool {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  category: string;
  isNew?: boolean;
  iconName: string;
}

export const FLAGSHIP_TOOLS: FlagshipTool[] = [
  { id: 'email-security-suite', name: 'Email Security Suite', slug: 'email-security-suite', tagline: 'SPF, DKIM, DMARC & BIMI deliverability audit', category: 'Email Security', isNew: true, iconName: 'Mail' },
  { id: 'csp-evaluator-builder', name: 'CSP Visual Evaluator & Builder', slug: 'csp-evaluator-builder', tagline: 'CSP header builder & XSS filter validator', category: 'Web Security', isNew: true, iconName: 'ShieldAlert' },
  { id: 'jwt-security-auditor', name: 'JWT Security Auditor', slug: 'jwt-security-auditor', tagline: 'Decode & test weak HMAC secrets & algorithm flaws', category: 'API Security', isNew: true, iconName: 'Ticket' },
  { id: 'google-dork-builder', name: 'Google Dork Builder & OSINT Studio', slug: 'google-dork-builder', tagline: 'Construct OSINT search queries & dorks', category: 'OSINT', isNew: true, iconName: 'Search' },
  { id: 'ioc-defang-stix-studio', name: 'IOC Defang & STIX Studio', slug: 'ioc-defang-stix-studio', tagline: 'Sanitize URLs/IPs & export to STIX 2.1', category: 'Incident Response', isNew: true, iconName: 'Microscope' },
  { id: 'sigma-yara-studio', name: 'Sigma & YARA Studio', slug: 'sigma-yara-studio', tagline: 'Convert Sigma rules to Splunk/Elastic & validate YARA', category: 'SIEM', isNew: true, iconName: 'Code' },
  { id: 'linux-hardening-generator', name: 'Linux Hardening Generator', slug: 'linux-hardening-generator', tagline: 'CIS Benchmark Bash script generator', category: 'Linux', isNew: true, iconName: 'Terminal' },
  { id: 'tls-hardening-studio', name: 'TLS Hardening Studio', slug: 'tls-hardening-studio', tagline: 'Mozilla SSL config rule generator', category: 'SSL/TLS', isNew: true, iconName: 'Lock' },
  { id: 'mitre-attack-explorer', name: 'MITRE ATT&CK Explorer', slug: 'mitre-attack-explorer', tagline: 'TTP matrix explorer & detection mapper', category: 'Threat Intelligence', isNew: true, iconName: 'Grid' },
  { id: 'browser-security-studio', name: 'Browser Security Studio', slug: 'browser-security-studio', tagline: 'HTTP response header auditor & grader', category: 'Web Security', isNew: false, iconName: 'Globe' }
];

export const TOOLS_REGISTRY: ToolMetadata[] = [
  {
    id: 'email-security-suite',
    name: 'Email Security Suite',
    slug: 'email-security-suite',
    tagline: 'SPF, DKIM, DMARC & BIMI deliverability audit',
    description: 'Unified anti-spoofing audit pipeline. Validate SPF 10-lookup limits, DKIM records, DMARC enforcement policies, BIMI branding, and MX mail server TLS configurations in a single browser-side check.',
    category: 'email-security',
    secondaryCategories: ['dns', 'compliance'],
    tags: ['spf', 'dkim', 'dmarc', 'bimi', 'email', 'phishing', 'security'],
    iconName: 'Mail',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (2s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [
      { question: 'What is the SPF 10-DNS lookup limit?', answer: 'RFC 7208 mandates that an SPF evaluation must not require more than 10 DNS lookups.' }
    ],
    relatedToolIds: ['dns-lookup', 'http-headers', 'ssl-checker'],
    relatedBlogSlugs: ['spf-dkim-dmarc-blueprint']
  },
  {
    id: 'csp-evaluator-builder',
    name: 'CSP Visual Evaluator & Builder',
    slug: 'csp-evaluator-builder',
    tagline: 'CSP header builder & XSS filter validator',
    description: 'Design, test, and validate Content Security Policy headers to mitigate Cross-Site Scripting (XSS) and clickjacking attacks.',
    category: 'web-security',
    secondaryCategories: ['ssl-tls'],
    tags: ['csp', 'xss', 'headers', 'security'],
    iconName: 'ShieldAlert',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['browser-security-studio', 'ssl-checker'],
    relatedBlogSlugs: []
  },
  {
    id: 'jwt-security-auditor',
    name: 'JWT Security Auditor',
    slug: 'jwt-security-auditor',
    tagline: 'Decode & test weak HMAC secrets & algorithm flaws',
    description: 'Audit JSON Web Token structures, check signature algorithms, detect algorithm confusion risks, and test HMAC secret strength privately.',
    category: 'api-security',
    secondaryCategories: ['web-security'],
    tags: ['jwt', 'token', 'auth', 'crypto'],
    iconName: 'Ticket',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['ssl-checker'],
    relatedBlogSlugs: []
  },
  {
    id: 'google-dork-builder',
    name: 'Google Dork Query Builder & OSINT Studio',
    slug: 'google-dork-builder',
    tagline: 'Construct OSINT search queries & dorks',
    description: 'Construct targeted search operator dorks for security audits, shadow IT discovery, and passive asset reconnaissance.',
    category: 'osint',
    secondaryCategories: ['web-security'],
    tags: ['dork', 'google', 'osint', 'recon'],
    iconName: 'Search',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['subdomain-finder', 'whois'],
    relatedBlogSlugs: []
  },
  {
    id: 'ioc-defang-stix-studio',
    name: 'IOC Defang & STIX Studio',
    slug: 'ioc-defang-stix-studio',
    tagline: 'Sanitize URLs/IPs & export to STIX 2.1',
    description: 'Sanitize malicious indicators of compromise (URLs, IPs, emails) for safe sharing in SOC reports and incident documentation.',
    category: 'incident-response',
    secondaryCategories: ['threat-intelligence'],
    tags: ['defang', 'ioc', 'stix', 'threat'],
    iconName: 'Microscope',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['vulnerability-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'sigma-yara-studio',
    name: 'Sigma & YARA Studio',
    slug: 'sigma-yara-studio',
    tagline: 'Convert Sigma rules to Splunk/Elastic & validate YARA',
    description: 'Translate open-source Sigma detection rules into Splunk, Elastic, and Sentinel queries automatically.',
    category: 'siem',
    secondaryCategories: ['threat-intelligence'],
    tags: ['sigma', 'yara', 'splunk', 'elastic'],
    iconName: 'Code',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['mitre-attack-explorer'],
    relatedBlogSlugs: []
  },
  {
    id: 'linux-hardening-generator',
    name: 'Linux Hardening Generator',
    slug: 'linux-hardening-generator',
    tagline: 'CIS Benchmark Bash script generator',
    description: 'Construct automated Bash hardening scripts for Ubuntu, Debian, and RHEL server baselines.',
    category: 'linux',
    secondaryCategories: ['compliance'],
    tags: ['linux', 'cis', 'hardening', 'ssh'],
    iconName: 'Terminal',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['port-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'tls-hardening-studio',
    name: 'TLS Hardening Studio',
    slug: 'tls-hardening-studio',
    tagline: 'Mozilla SSL config rule generator',
    description: 'Construct Mozilla-compliant TLS 1.2 and 1.3 web server encryption configurations.',
    category: 'ssl-tls',
    secondaryCategories: ['web-security'],
    tags: ['tls', 'ssl', 'nginx', 'apache'],
    iconName: 'Lock',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['ssl-checker'],
    relatedBlogSlugs: []
  },
  {
    id: 'mitre-attack-explorer',
    name: 'MITRE ATT&CK Explorer',
    slug: 'mitre-attack-explorer',
    tagline: 'TTP matrix explorer & detection mapper',
    description: 'Browse enterprise adversary tactics, techniques, and procedures (TTPs) mapped directly to defensive detection rules.',
    category: 'threat-intelligence',
    secondaryCategories: ['siem'],
    tags: ['mitre', 'attack', 'ttp', 'matrix'],
    iconName: 'Grid',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    faqs: [],
    relatedToolIds: ['sigma-yara-studio'],
    relatedBlogSlugs: []
  },
  {
    id: 'browser-security-studio',
    name: 'Browser Security Studio',
    slug: 'browser-security-studio',
    tagline: 'HTTP response header auditor & grader',
    description: 'Inspect HTTP response headers for Content-Security-Policy, HSTS, X-Frame-Options, and X-Content-Type-Options.',
    category: 'web-security',
    secondaryCategories: ['ssl-tls'],
    tags: ['headers', 'csp', 'hsts', 'xss'],
    iconName: 'Globe',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    isNew: false,
    faqs: [],
    relatedToolIds: ['csp-evaluator-builder', 'ssl-checker'],
    relatedBlogSlugs: []
  },
  {
    id: 'whois',
    name: 'WHOIS Lookup',
    slug: 'whois',
    tagline: 'Domain ownership and registrar intelligence',
    description: 'Query official domain registration records, registrar details, creation dates, expiration deadlines, and nameservers.',
    category: 'whois',
    secondaryCategories: ['domains', 'osint'],
    tags: ['whois', 'domain', 'registrar', 'osint', 'free', 'instant'],
    iconName: 'Search',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['dns-lookup', 'subdomain-finder', 'ssl-checker'],
    relatedBlogSlugs: []
  },
  {
    id: 'port-scanner',
    name: 'Port Scanner',
    slug: 'port-scanner',
    tagline: 'Detect open ports and exposed network services',
    description: 'Audit network interfaces to detect open TCP ports, running services, and potential entry points.',
    category: 'networking',
    secondaryCategories: ['web-security'],
    tags: ['nmap', 'port', 'tcp', 'scanner', 'firewall', 'network'],
    iconName: 'Terminal',
    difficulty: 'Intermediate',
    estimatedTime: '3-5 seconds',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['whois', 'vulnerability-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'ssl-checker',
    name: 'SSL Certificate Checker',
    slug: 'ssl-checker',
    tagline: 'Audit SSL/TLS certificate validity and chain',
    description: 'Inspect HTTPS certificate validity, expiration dates, issuing Certificate Authority (CA), SAN domains, and TLS ciphers.',
    category: 'ssl-tls',
    secondaryCategories: ['certificates'],
    tags: ['ssl', 'tls', 'https', 'certificate'],
    iconName: 'Lock',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (2s)',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['dns-lookup', 'vulnerability-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    slug: 'dns-lookup',
    tagline: 'Comprehensive DNS record resolution and analysis',
    description: 'Query A, AAAA, MX, TXT, CNAME, NS, SOA, and CAA records across global authoritative DNS servers.',
    category: 'dns',
    secondaryCategories: ['domains'],
    tags: ['dns', 'records', 'mx', 'txt'],
    iconName: 'Globe',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['whois', 'subdomain-finder'],
    relatedBlogSlugs: []
  },
  {
    id: 'http-headers',
    name: 'HTTP Security Headers',
    slug: 'http-headers',
    tagline: 'Evaluate security header configurations and grades',
    description: 'Inspect HTTP response headers for Content-Security-Policy, HSTS, X-Frame-Options, and X-Content-Type-Options.',
    category: 'web-security',
    secondaryCategories: ['ssl-tls'],
    tags: ['headers', 'csp', 'hsts', 'xss'],
    iconName: 'ShieldAlert',
    difficulty: 'Intermediate',
    estimatedTime: 'Instant (2s)',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['ssl-checker', 'vulnerability-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'subdomain-finder',
    name: 'Subdomain Finder',
    slug: 'subdomain-finder',
    tagline: 'Discover public subdomains and attack surface assets',
    description: 'Perform passive subdomain enumeration using Certificate Transparency logs and public asset intelligence.',
    category: 'domains',
    secondaryCategories: ['osint'],
    tags: ['subdomain', 'enumeration', 'ct-logs'],
    iconName: 'Server',
    difficulty: 'Intermediate',
    estimatedTime: '2-4 seconds',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['whois', 'dns-lookup', 'port-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'tech-detector',
    name: 'Technology Detector',
    slug: 'tech-detector',
    tagline: 'Identify CMS, web frameworks, CDNs, and server stack',
    description: 'Analyze web application headers, HTML DOM footprints, and JavaScript variables to uncover the underlying tech stack.',
    category: 'web-security',
    secondaryCategories: ['osint'],
    tags: ['wappalyzer', 'cms', 'framework'],
    iconName: 'Cpu',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (2s)',
    isPopular: true,
    faqs: [],
    relatedToolIds: ['vulnerability-scanner', 'subdomain-finder'],
    relatedBlogSlugs: []
  },
  {
    id: 'ip-lookup',
    name: 'IP & ASN Intelligence',
    slug: 'ip-lookup',
    tagline: 'IP geolocation, ASN routing, and ISP identification',
    description: 'Query IP addresses for Autonomous System Numbers (ASN), BGP network range, ISP owner, country location, and threat reputation.',
    category: 'ip-intelligence',
    secondaryCategories: ['networking'],
    tags: ['ip', 'asn', 'geolocation'],
    iconName: 'Radio',
    difficulty: 'Beginner',
    estimatedTime: 'Instant (1s)',
    isPopular: true,
    faqs: [],
    relatedToolIds: ['whois', 'dns-lookup', 'port-scanner'],
    relatedBlogSlugs: []
  },
  {
    id: 'vulnerability-scanner',
    name: 'Vulnerability Scanner',
    slug: 'vulnerability-scanner',
    tagline: 'Identify web security weaknesses and misconfigurations',
    description: 'Run automated passive diagnostics to uncover missing security headers, outdated SSL protocols, and exposed administrative paths.',
    category: 'web-security',
    secondaryCategories: ['ssl-tls'],
    tags: ['vulnerability', 'scan', 'owasp'],
    iconName: 'ShieldAlert',
    difficulty: 'Intermediate',
    estimatedTime: '3-6 seconds',
    isPopular: true,
    isFeatured: true,
    faqs: [],
    relatedToolIds: ['ssl-checker', 'port-scanner'],
    relatedBlogSlugs: []
  }
];

export function getToolById(id: string): ToolMetadata | undefined {
  return TOOLS_REGISTRY.find(t => t.id === id || t.slug === id);
}

export function getToolsByCategory(category: string): ToolMetadata[] {
  return TOOLS_REGISTRY.filter(t => t.category === category || t.secondaryCategories?.includes(category as any));
}
