import Link from 'next/link';
import { AlertTriangle, ChevronRight } from 'lucide-react';

export const metadata = {
  title: 'Legal Disclaimer | ReconShield Cybersecurity',
  description: 'Legal disclaimer for ReconShield. Information provided is for educational and defensive cybersecurity purposes only.',
  alternates: {
    canonical: 'https://reconshield.in/disclaimer',
  }
};

export default function DisclaimerPage() {
  const lastUpdated = "May 26, 2026";

  return (
    <div className="bg-[#05080f] min-h-screen pb-24">
      {/* Header */}
      <section className="relative pt-24 pb-16 border-b border-white/5 overflow-hidden">
        <div className="absolute inset-0 bg-[#0a0d14] -z-20" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-3xl h-[400px] bg-red-500/5 blur-[100px] rounded-full pointer-events-none -z-10" />
        
        <div className="max-w-[1000px] mx-auto px-6">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center justify-center shrink-0">
              <AlertTriangle className="w-6 h-6 text-red-500" />
            </div>
            <div>
              <h1 className="text-3xl md:text-5xl font-display font-bold text-white mb-2">Legal Disclaimer</h1>
              <p className="text-gray-400 font-mono text-xs uppercase tracking-widest">Last Updated: {lastUpdated}</p>
            </div>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="max-w-[1000px] mx-auto px-6 pt-16">
        <div className="prose prose-invert max-w-none prose-h2:text-2xl prose-h2:font-display prose-h2:text-white prose-h2:mt-12 prose-h2:mb-6 prose-p:text-gray-400 prose-p:leading-relaxed prose-a:text-red-400 prose-li:text-gray-400">
          
          <h2>Educational & Defensive Purpose Only</h2>
          <p>
            The information, tools, methodologies, and scripts provided on ReconShield (the "Platform") are intended strictly for <strong>educational, research, and defensive cybersecurity purposes</strong>. 
          </p>
          <p>
            ReconShield was built to help system administrators, security engineers, and developers understand their external attack surface and secure their infrastructure against modern cyber threats.
          </p>

          <h2>No Liability</h2>
          <p>
            The creator(s), author(s), and publisher(s) of this Platform accept <strong>NO RESPONSIBILITY OR LIABILITY</strong> for any misuse, damage, or illegal actions caused directly or indirectly by the information or tools provided. 
          </p>
          <p>
            By using this Platform, you acknowledge that you are using these tools at your own risk. It is the end user's responsibility to obey all applicable local, state, and federal laws regarding network scanning, reconnaissance, and data privacy.
          </p>

          <h2>Authorization Requirement</h2>
          <p>
            You must have explicit, written authorization from the target network/domain owner before utilizing any active scanning methodologies. While ReconShield relies on passive, non-intrusive Open Source Intelligence (OSINT) and DNS queries, the user assumes all liability regarding the targets they choose to investigate.
          </p>

          <h2>"As-Is" Provision</h2>
          <p>
            All intelligence, vulnerability definitions, and security scores generated by ReconShield are provided on an "AS-IS" basis without warranties of any kind, either express or implied. Threat intelligence is dynamic; therefore, ReconShield does not guarantee the complete accuracy, timeliness, or reliability of any scan results or third-party threat feeds.
          </p>

          <h2>Advertising & Affiliate Disclaimer</h2>
          <p>
            ReconShield utilizes third-party advertising networks (such as Google AdSense) to fund the server infrastructure required to keep these tools free. The presence of an advertisement does not imply an endorsement of the advertised product or service by ReconShield.
          </p>

        </div>

        <div className="mt-16 pt-8 border-t border-white/5 flex gap-4">
          <Link href="/privacy" className="text-sm font-mono text-gray-500 hover:text-white transition-colors flex items-center gap-2">
             Privacy Policy <ChevronRight className="w-4 h-4" />
          </Link>
          <Link href="/terms" className="text-sm font-mono text-gray-500 hover:text-white transition-colors flex items-center gap-2">
             Terms of Service <ChevronRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
    </div>
  );
}
